"""Official FIFA World Cup 2026 knockout-stage allocation rules.

The third-place allocation table is transcribed from Annexe C of the FIFA World
Cup 2026 Regulations (495 possible combinations).  The mapping columns are the
eight group winners that face a best third-placed team: 1A, 1B, 1D, 1E, 1G, 1I,
1K and 1L.
"""

from __future__ import annotations

from typing import Any

THIRD_PLACE_COLUMNS = ("A", "B", "D", "E", "G", "I", "K", "L")

# Key: the eight qualifying third-place group letters in alphabetical order.
# Value: assigned third-place group letters in THIRD_PLACE_COLUMNS order.
FIFA_2026_THIRD_PLACE_ALLOCATION: dict[str, str] = {
  "ABCDEFGH": "HGBCAFDE",
  "ABCDEFGI": "CGBDAFEI",
  "ABCDEFGJ": "CGBDAFEJ",
  "ABCDEFGK": "CGBDAFEK",
  "ABCDEFGL": "CGBDAFLE",
  "ABCDEFHI": "HEBCAFDI",
  "ABCDEFHJ": "HJBCAFDE",
  "ABCDEFHK": "HEBCAFDK",
  "ABCDEFHL": "HFBCADLE",
  "ABCDEFIJ": "CJBDAFEI",
  "ABCDEFIK": "CEBDAFIK",
  "ABCDEFIL": "CEBDAFLI",
  "ABCDEFJK": "CJBDAFEK",
  "ABCDEFJL": "CJBDAFLE",
  "ABCDEFKL": "CEBDAFLK",
  "ABCDEGHI": "HGBCADEI",
  "ABCDEGHJ": "HGBCADEJ",
  "ABCDEGHK": "HGBCADEK",
  "ABCDEGHL": "HGBCADLE",
  "ABCDEGIJ": "EGBCADIJ",
  "ABCDEGIK": "EGBCADIK",
  "ABCDEGIL": "EGBCADLI",
  "ABCDEGJK": "EGBCADJK",
  "ABCDEGJL": "EGBCADLJ",
  "ABCDEGKL": "EGBCADLK",
  "ABCDEHIJ": "HJBCADEI",
  "ABCDEHIK": "HEBCADIK",
  "ABCDEHIL": "HEBCADLI",
  "ABCDEHJK": "HJBCADEK",
  "ABCDEHJL": "HJBCADLE",
  "ABCDEHKL": "HEBCADLK",
  "ABCDEIJK": "EJBCADIK",
  "ABCDEIJL": "EJBCADLI",
  "ABCDEIKL": "EIBCADLK",
  "ABCDEJKL": "EJBCADLK",
  "ABCDFGHI": "HGBCAFDI",
  "ABCDFGHJ": "HGBCAFDJ",
  "ABCDFGHK": "HGBCAFDK",
  "ABCDFGHL": "CGBDAFLH",
  "ABCDFGIJ": "CGBDAFIJ",
  "ABCDFGIK": "CGBDAFIK",
  "ABCDFGIL": "CGBDAFLI",
  "ABCDFGJK": "CGBDAFJK",
  "ABCDFGJL": "CGBDAFLJ",
  "ABCDFGKL": "CGBDAFLK",
  "ABCDFHIJ": "HJBCAFDI",
  "ABCDFHIK": "HFBCADIK",
  "ABCDFHIL": "HFBCADLI",
  "ABCDFHJK": "HJBCAFDK",
  "ABCDFHJL": "CJBDAFLH",
  "ABCDFHKL": "HFBCADLK",
  "ABCDFIJK": "CJBDAFIK",
  "ABCDFIJL": "CJBDAFLI",
  "ABCDFIKL": "CIBDAFLK",
  "ABCDFJKL": "CJBDAFLK",
  "ABCDGHIJ": "HGBCADIJ",
  "ABCDGHIK": "HGBCADIK",
  "ABCDGHIL": "HGBCADLI",
  "ABCDGHJK": "HGBCADJK",
  "ABCDGHJL": "HGBCADLJ",
  "ABCDGHKL": "HGBCADLK",
  "ABCDGIJK": "CJBDAGIK",
  "ABCDGIJL": "CJBDAGLI",
  "ABCDGIKL": "IGBCADLK",
  "ABCDGJKL": "CJBDAGLK",
  "ABCDHIJK": "HJBCADIK",
  "ABCDHIJL": "HJBCADLI",
  "ABCDHIKL": "HIBCADLK",
  "ABCDHJKL": "HJBCADLK",
  "ABCDIJKL": "IJBCADLK",
  "ABCEFGHI": "HGBCAFEI",
  "ABCEFGHJ": "HGBCAFEJ",
  "ABCEFGHK": "HGBCAFEK",
  "ABCEFGHL": "HGBCAFLE",
  "ABCEFGIJ": "EGBCAFIJ",
  "ABCEFGIK": "EGBCAFIK",
  "ABCEFGIL": "EGBCAFLI",
  "ABCEFGJK": "EGBCAFJK",
  "ABCEFGJL": "EGBCAFLJ",
  "ABCEFGKL": "EGBCAFLK",
  "ABCEFHIJ": "HJBCAFEI",
  "ABCEFHIK": "HEBCAFIK",
  "ABCEFHIL": "HEBCAFLI",
  "ABCEFHJK": "HJBCAFEK",
  "ABCEFHJL": "HJBCAFLE",
  "ABCEFHKL": "HEBCAFLK",
  "ABCEFIJK": "EJBCAFIK",
  "ABCEFIJL": "EJBCAFLI",
  "ABCEFIKL": "EIBCAFLK",
  "ABCEFJKL": "EJBCAFLK",
  "ABCEGHIJ": "HJBCAGEI",
  "ABCEGHIK": "EGBCAHIK",
  "ABCEGHIL": "EGBCAHLI",
  "ABCEGHJK": "HJBCAGEK",
  "ABCEGHJL": "HJBCAGLE",
  "ABCEGHKL": "EGBCAHLK",
  "ABCEGIJK": "EJBCAGIK",
  "ABCEGIJL": "EJBCAGLI",
  "ABCEGIKL": "EGBAICLK",
  "ABCEGJKL": "EJBCAGLK",
  "ABCEHIJK": "EJBCAHIK",
  "ABCEHIJL": "EJBCAHLI",
  "ABCEHIKL": "EIBCAHLK",
  "ABCEHJKL": "EJBCAHLK",
  "ABCEIJKL": "EJBAICLK",
  "ABCFGHIJ": "HGBCAFIJ",
  "ABCFGHIK": "HGBCAFIK",
  "ABCFGHIL": "HGBCAFLI",
  "ABCFGHJK": "HGBCAFJK",
  "ABCFGHJL": "HGBCAFLJ",
  "ABCFGHKL": "HGBCAFLK",
  "ABCFGIJK": "CJBFAGIK",
  "ABCFGIJL": "CJBFAGLI",
  "ABCFGIKL": "IGBCAFLK",
  "ABCFGJKL": "CJBFAGLK",
  "ABCFHIJK": "HJBCAFIK",
  "ABCFHIJL": "HJBCAFLI",
  "ABCFHIKL": "HIBCAFLK",
  "ABCFHJKL": "HJBCAFLK",
  "ABCFIJKL": "IJBCAFLK",
  "ABCGHIJK": "HJBCAGIK",
  "ABCGHIJL": "HJBCAGLI",
  "ABCGHIKL": "IGBCAHLK",
  "ABCGHJKL": "HJBCAGLK",
  "ABCGIJKL": "IJBCAGLK",
  "ABCHIJKL": "IJBCAHLK",
  "ABDEFGHI": "HGBDAFEI",
  "ABDEFGHJ": "HGBDAFEJ",
  "ABDEFGHK": "HGBDAFEK",
  "ABDEFGHL": "HGBDAFLE",
  "ABDEFGIJ": "EGBDAFIJ",
  "ABDEFGIK": "EGBDAFIK",
  "ABDEFGIL": "EGBDAFLI",
  "ABDEFGJK": "EGBDAFJK",
  "ABDEFGJL": "EGBDAFLJ",
  "ABDEFGKL": "EGBDAFLK",
  "ABDEFHIJ": "HJBDAFEI",
  "ABDEFHIK": "HEBDAFIK",
  "ABDEFHIL": "HEBDAFLI",
  "ABDEFHJK": "HJBDAFEK",
  "ABDEFHJL": "HJBDAFLE",
  "ABDEFHKL": "HEBDAFLK",
  "ABDEFIJK": "EJBDAFIK",
  "ABDEFIJL": "EJBDAFLI",
  "ABDEFIKL": "EIBDAFLK",
  "ABDEFJKL": "EJBDAFLK",
  "ABDEGHIJ": "HJBDAGEI",
  "ABDEGHIK": "EGBDAHIK",
  "ABDEGHIL": "EGBDAHLI",
  "ABDEGHJK": "HJBDAGEK",
  "ABDEGHJL": "HJBDAGLE",
  "ABDEGHKL": "EGBDAHLK",
  "ABDEGIJK": "EJBDAGIK",
  "ABDEGIJL": "EJBDAGLI",
  "ABDEGIKL": "EGBAIDLK",
  "ABDEGJKL": "EJBDAGLK",
  "ABDEHIJK": "EJBDAHIK",
  "ABDEHIJL": "EJBDAHLI",
  "ABDEHIKL": "EIBDAHLK",
  "ABDEHJKL": "EJBDAHLK",
  "ABDEIJKL": "EJBAIDLK",
  "ABDFGHIJ": "HGBDAFIJ",
  "ABDFGHIK": "HGBDAFIK",
  "ABDFGHIL": "HGBDAFLI",
  "ABDFGHJK": "HGBDAFJK",
  "ABDFGHJL": "HGBDAFLJ",
  "ABDFGHKL": "HGBDAFLK",
  "ABDFGIJK": "FJBDAGIK",
  "ABDFGIJL": "FJBDAGLI",
  "ABDFGIKL": "IGBDAFLK",
  "ABDFGJKL": "FJBDAGLK",
  "ABDFHIJK": "HJBDAFIK",
  "ABDFHIJL": "HJBDAFLI",
  "ABDFHIKL": "HIBDAFLK",
  "ABDFHJKL": "HJBDAFLK",
  "ABDFIJKL": "IJBDAFLK",
  "ABDGHIJK": "HJBDAGIK",
  "ABDGHIJL": "HJBDAGLI",
  "ABDGHIKL": "IGBDAHLK",
  "ABDGHJKL": "HJBDAGLK",
  "ABDGIJKL": "IJBDAGLK",
  "ABDHIJKL": "IJBDAHLK",
  "ABEFGHIJ": "HJBFAGEI",
  "ABEFGHIK": "EGBFAHIK",
  "ABEFGHIL": "EGBFAHLI",
  "ABEFGHJK": "HJBFAGEK",
  "ABEFGHJL": "HJBFAGLE",
  "ABEFGHKL": "EGBFAHLK",
  "ABEFGIJK": "EJBFAGIK",
  "ABEFGIJL": "EJBFAGLI",
  "ABEFGIKL": "EGBAIFLK",
  "ABEFGJKL": "EJBFAGLK",
  "ABEFHIJK": "EJBFAHIK",
  "ABEFHIJL": "EJBFAHLI",
  "ABEFHIKL": "EIBFAHLK",
  "ABEFHJKL": "EJBFAHLK",
  "ABEFIJKL": "EJBAIFLK",
  "ABEGHIJK": "EJBAHGIK",
  "ABEGHIJL": "EJBAHGLI",
  "ABEGHIKL": "EGBAIHLK",
  "ABEGHJKL": "EJBAHGLK",
  "ABEGIJKL": "EJBAIGLK",
  "ABEHIJKL": "EJBAIHLK",
  "ABFGHIJK": "HJBFAGIK",
  "ABFGHIJL": "HJBFAGLI",
  "ABFGHIKL": "HGBAIFLK",
  "ABFGHJKL": "HJBFAGLK",
  "ABFGIJKL": "IJBFAGLK",
  "ABFHIJKL": "HJBAIFLK",
  "ABGHIJKL": "HJBAIGLK",
  "ACDEFGHI": "HGECAFDI",
  "ACDEFGHJ": "HGJCAFDE",
  "ACDEFGHK": "HGECAFDK",
  "ACDEFGHL": "HGFCADLE",
  "ACDEFGIJ": "CGJDAFEI",
  "ACDEFGIK": "CGEDAFIK",
  "ACDEFGIL": "CGEDAFLI",
  "ACDEFGJK": "CGJDAFEK",
  "ACDEFGJL": "CGJDAFLE",
  "ACDEFGKL": "CGEDAFLK",
  "ACDEFHIJ": "HJECAFDI",
  "ACDEFHIK": "HEFCADIK",
  "ACDEFHIL": "HEFCADLI",
  "ACDEFHJK": "HJECAFDK",
  "ACDEFHJL": "HJFCADLE",
  "ACDEFHKL": "HEFCADLK",
  "ACDEFIJK": "CJEDAFIK",
  "ACDEFIJL": "CJEDAFLI",
  "ACDEFIKL": "CEIDAFLK",
  "ACDEFJKL": "CJEDAFLK",
  "ACDEGHIJ": "HGJCADEI",
  "ACDEGHIK": "HGECADIK",
  "ACDEGHIL": "HGECADLI",
  "ACDEGHJK": "HGJCADEK",
  "ACDEGHJL": "HGJCADLE",
  "ACDEGHKL": "HGECADLK",
  "ACDEGIJK": "EGJCADIK",
  "ACDEGIJL": "EGJCADLI",
  "ACDEGIKL": "EGICADLK",
  "ACDEGJKL": "EGJCADLK",
  "ACDEHIJK": "HJECADIK",
  "ACDEHIJL": "HJECADLI",
  "ACDEHIKL": "HEICADLK",
  "ACDEHJKL": "HJECADLK",
  "ACDEIJKL": "EJICADLK",
  "ACDFGHIJ": "HGJCAFDI",
  "ACDFGHIK": "HGFCADIK",
  "ACDFGHIL": "HGFCADLI",
  "ACDFGHJK": "HGJCAFDK",
  "ACDFGHJL": "CGJDAFLH",
  "ACDFGHKL": "HGFCADLK",
  "ACDFGIJK": "CGJDAFIK",
  "ACDFGIJL": "CGJDAFLI",
  "ACDFGIKL": "CGIDAFLK",
  "ACDFGJKL": "CGJDAFLK",
  "ACDFHIJK": "HJFCADIK",
  "ACDFHIJL": "HJFCADLI",
  "ACDFHIKL": "HFICADLK",
  "ACDFHJKL": "HJFCADLK",
  "ACDFIJKL": "CJIDAFLK",
  "ACDGHIJK": "HGJCADIK",
  "ACDGHIJL": "HGJCADLI",
  "ACDGHIKL": "HGICADLK",
  "ACDGHJKL": "HGJCADLK",
  "ACDGIJKL": "IGJCADLK",
  "ACDHIJKL": "HJICADLK",
  "ACEFGHIJ": "HGJCAFEI",
  "ACEFGHIK": "HGECAFIK",
  "ACEFGHIL": "HGECAFLI",
  "ACEFGHJK": "HGJCAFEK",
  "ACEFGHJL": "HGJCAFLE",
  "ACEFGHKL": "HGECAFLK",
  "ACEFGIJK": "EGJCAFIK",
  "ACEFGIJL": "EGJCAFLI",
  "ACEFGIKL": "EGICAFLK",
  "ACEFGJKL": "EGJCAFLK",
  "ACEFHIJK": "HJECAFIK",
  "ACEFHIJL": "HJECAFLI",
  "ACEFHIKL": "HEICAFLK",
  "ACEFHJKL": "HJECAFLK",
  "ACEFIJKL": "EJICAFLK",
  "ACEGHIJK": "EGJCAHIK",
  "ACEGHIJL": "EGJCAHLI",
  "ACEGHIKL": "EGICAHLK",
  "ACEGHJKL": "EGJCAHLK",
  "ACEGIJKL": "EJICAGLK",
  "ACEHIJKL": "EJICAHLK",
  "ACFGHIJK": "HGJCAFIK",
  "ACFGHIJL": "HGJCAFLI",
  "ACFGHIKL": "HGICAFLK",
  "ACFGHJKL": "HGJCAFLK",
  "ACFGIJKL": "IGJCAFLK",
  "ACFHIJKL": "HJICAFLK",
  "ACGHIJKL": "HJICAGLK",
  "ADEFGHIJ": "HGJDAFEI",
  "ADEFGHIK": "HGEDAFIK",
  "ADEFGHIL": "HGEDAFLI",
  "ADEFGHJK": "HGJDAFEK",
  "ADEFGHJL": "HGJDAFLE",
  "ADEFGHKL": "HGEDAFLK",
  "ADEFGIJK": "EGJDAFIK",
  "ADEFGIJL": "EGJDAFLI",
  "ADEFGIKL": "EGIDAFLK",
  "ADEFGJKL": "EGJDAFLK",
  "ADEFHIJK": "HJEDAFIK",
  "ADEFHIJL": "HJEDAFLI",
  "ADEFHIKL": "HEIDAFLK",
  "ADEFHJKL": "HJEDAFLK",
  "ADEFIJKL": "EJIDAFLK",
  "ADEGHIJK": "EGJDAHIK",
  "ADEGHIJL": "EGJDAHLI",
  "ADEGHIKL": "EGIDAHLK",
  "ADEGHJKL": "EGJDAHLK",
  "ADEGIJKL": "EJIDAGLK",
  "ADEHIJKL": "EJIDAHLK",
  "ADFGHIJK": "HGJDAFIK",
  "ADFGHIJL": "HGJDAFLI",
  "ADFGHIKL": "HGIDAFLK",
  "ADFGHJKL": "HGJDAFLK",
  "ADFGIJKL": "IGJDAFLK",
  "ADFHIJKL": "HJIDAFLK",
  "ADGHIJKL": "HJIDAGLK",
  "AEFGHIJK": "EGJFAHIK",
  "AEFGHIJL": "EGJFAHLI",
  "AEFGHIKL": "EGIFAHLK",
  "AEFGHJKL": "EGJFAHLK",
  "AEFGIJKL": "EJIFAGLK",
  "AEFHIJKL": "EJIFAHLK",
  "AEGHIJKL": "EJIAHGLK",
  "AFGHIJKL": "HJIFAGLK",
  "BCDEFGHI": "CGBDHFEI",
  "BCDEFGHJ": "HGBCJFDE",
  "BCDEFGHK": "CGBDHFEK",
  "BCDEFGHL": "CGBDHFLE",
  "BCDEFGIJ": "CGBDJFEI",
  "BCDEFGIK": "CGBDEFIK",
  "BCDEFGIL": "CGBDEFLI",
  "BCDEFGJK": "CGBDJFEK",
  "BCDEFGJL": "CGBDJFLE",
  "BCDEFGKL": "CGBDEFLK",
  "BCDEFHIJ": "CJBDHFEI",
  "BCDEFHIK": "CEBDHFIK",
  "BCDEFHIL": "CEBDHFLI",
  "BCDEFHJK": "CJBDHFEK",
  "BCDEFHJL": "CJBDHFLE",
  "BCDEFHKL": "CEBDHFLK",
  "BCDEFIJK": "CJBDEFIK",
  "BCDEFIJL": "CJBDEFLI",
  "BCDEFIKL": "CEBDIFLK",
  "BCDEFJKL": "CJBDEFLK",
  "BCDEGHIJ": "HGBCJDEI",
  "BCDEGHIK": "EGBCHDIK",
  "BCDEGHIL": "EGBCHDLI",
  "BCDEGHJK": "HGBCJDEK",
  "BCDEGHJL": "HGBCJDLE",
  "BCDEGHKL": "EGBCHDLK",
  "BCDEGIJK": "EGBCJDIK",
  "BCDEGIJL": "EGBCJDLI",
  "BCDEGIKL": "EGBCIDLK",
  "BCDEGJKL": "EGBCJDLK",
  "BCDEHIJK": "EJBCHDIK",
  "BCDEHIJL": "EJBCHDLI",
  "BCDEHIKL": "EIBCHDLK",
  "BCDEHJKL": "EJBCHDLK",
  "BCDEIJKL": "EJBCIDLK",
  "BCDFGHIJ": "HGBCJFDI",
  "BCDFGHIK": "CGBDHFIK",
  "BCDFGHIL": "CGBDHFLI",
  "BCDFGHJK": "HGBCJFDK",
  "BCDFGHJL": "CGBDHFLJ",
  "BCDFGHKL": "CGBDHFLK",
  "BCDFGIJK": "CGBDJFIK",
  "BCDFGIJL": "CGBDJFLI",
  "BCDFGIKL": "CGBDIFLK",
  "BCDFGJKL": "CGBDJFLK",
  "BCDFHIJK": "CJBDHFIK",
  "BCDFHIJL": "CJBDHFLI",
  "BCDFHIKL": "CIBDHFLK",
  "BCDFHJKL": "CJBDHFLK",
  "BCDFIJKL": "CJBDIFLK",
  "BCDGHIJK": "HGBCJDIK",
  "BCDGHIJL": "HGBCJDLI",
  "BCDGHIKL": "HGBCIDLK",
  "BCDGHJKL": "HGBCJDLK",
  "BCDGIJKL": "IGBCJDLK",
  "BCDHIJKL": "HJBCIDLK",
  "BCEFGHIJ": "HGBCJFEI",
  "BCEFGHIK": "EGBCHFIK",
  "BCEFGHIL": "EGBCHFLI",
  "BCEFGHJK": "HGBCJFEK",
  "BCEFGHJL": "HGBCJFLE",
  "BCEFGHKL": "EGBCHFLK",
  "BCEFGIJK": "EGBCJFIK",
  "BCEFGIJL": "EGBCJFLI",
  "BCEFGIKL": "EGBCIFLK",
  "BCEFGJKL": "EGBCJFLK",
  "BCEFHIJK": "EJBCHFIK",
  "BCEFHIJL": "EJBCHFLI",
  "BCEFHIKL": "EIBCHFLK",
  "BCEFHJKL": "EJBCHFLK",
  "BCEFIJKL": "EJBCIFLK",
  "BCEGHIJK": "EJBCHGIK",
  "BCEGHIJL": "EJBCHGLI",
  "BCEGHIKL": "EGBCIHLK",
  "BCEGHJKL": "EJBCHGLK",
  "BCEGIJKL": "EJBCIGLK",
  "BCEHIJKL": "EJBCIHLK",
  "BCFGHIJK": "HGBCJFIK",
  "BCFGHIJL": "HGBCJFLI",
  "BCFGHIKL": "HGBCIFLK",
  "BCFGHJKL": "HGBCJFLK",
  "BCFGIJKL": "IGBCJFLK",
  "BCFHIJKL": "HJBCIFLK",
  "BCGHIJKL": "HJBCIGLK",
  "BDEFGHIJ": "HGBDJFEI",
  "BDEFGHIK": "EGBDHFIK",
  "BDEFGHIL": "EGBDHFLI",
  "BDEFGHJK": "HGBDJFEK",
  "BDEFGHJL": "HGBDJFLE",
  "BDEFGHKL": "EGBDHFLK",
  "BDEFGIJK": "EGBDJFIK",
  "BDEFGIJL": "EGBDJFLI",
  "BDEFGIKL": "EGBDIFLK",
  "BDEFGJKL": "EGBDJFLK",
  "BDEFHIJK": "EJBDHFIK",
  "BDEFHIJL": "EJBDHFLI",
  "BDEFHIKL": "EIBDHFLK",
  "BDEFHJKL": "EJBDHFLK",
  "BDEFIJKL": "EJBDIFLK",
  "BDEGHIJK": "EJBDHGIK",
  "BDEGHIJL": "EJBDHGLI",
  "BDEGHIKL": "EGBDIHLK",
  "BDEGHJKL": "EJBDHGLK",
  "BDEGIJKL": "EJBDIGLK",
  "BDEHIJKL": "EJBDIHLK",
  "BDFGHIJK": "HGBDJFIK",
  "BDFGHIJL": "HGBDJFLI",
  "BDFGHIKL": "HGBDIFLK",
  "BDFGHJKL": "HGBDJFLK",
  "BDFGIJKL": "IGBDJFLK",
  "BDFHIJKL": "HJBDIFLK",
  "BDGHIJKL": "HJBDIGLK",
  "BEFGHIJK": "EJBFHGIK",
  "BEFGHIJL": "EJBFHGLI",
  "BEFGHIKL": "EGBFIHLK",
  "BEFGHJKL": "EJBFHGLK",
  "BEFGIJKL": "EJBFIGLK",
  "BEFHIJKL": "EJBFIHLK",
  "BEGHIJKL": "EJIBHGLK",
  "BFGHIJKL": "HJBFIGLK",
  "CDEFGHIJ": "CGJDHFEI",
  "CDEFGHIK": "CGEDHFIK",
  "CDEFGHIL": "CGEDHFLI",
  "CDEFGHJK": "CGJDHFEK",
  "CDEFGHJL": "CGJDHFLE",
  "CDEFGHKL": "CGEDHFLK",
  "CDEFGIJK": "CGEDJFIK",
  "CDEFGIJL": "CGEDJFLI",
  "CDEFGIKL": "CGEDIFLK",
  "CDEFGJKL": "CGEDJFLK",
  "CDEFHIJK": "CJEDHFIK",
  "CDEFHIJL": "CJEDHFLI",
  "CDEFHIKL": "CEIDHFLK",
  "CDEFHJKL": "CJEDHFLK",
  "CDEFIJKL": "CJEDIFLK",
  "CDEGHIJK": "EGJCHDIK",
  "CDEGHIJL": "EGJCHDLI",
  "CDEGHIKL": "EGICHDLK",
  "CDEGHJKL": "EGJCHDLK",
  "CDEGIJKL": "EGICJDLK",
  "CDEHIJKL": "EJICHDLK",
  "CDFGHIJK": "CGJDHFIK",
  "CDFGHIJL": "CGJDHFLI",
  "CDFGHIKL": "CGIDHFLK",
  "CDFGHJKL": "CGJDHFLK",
  "CDFGIJKL": "CGIDJFLK",
  "CDFHIJKL": "CJIDHFLK",
  "CDGHIJKL": "HGICJDLK",
  "CEFGHIJK": "EGJCHFIK",
  "CEFGHIJL": "EGJCHFLI",
  "CEFGHIKL": "EGICHFLK",
  "CEFGHJKL": "EGJCHFLK",
  "CEFGIJKL": "EGICJFLK",
  "CEFHIJKL": "EJICHFLK",
  "CEGHIJKL": "EJICHGLK",
  "CFGHIJKL": "HGICJFLK",
  "DEFGHIJK": "EGJDHFIK",
  "DEFGHIJL": "EGJDHFLI",
  "DEFGHIKL": "EGIDHFLK",
  "DEFGHJKL": "EGJDHFLK",
  "DEFGIJKL": "EGIDJFLK",
  "DEFHIJKL": "EJIDHFLK",
  "DEGHIJKL": "EJIDHGLK",
  "DFGHIJKL": "HGIDJFLK",
  "EFGHIJKL": "EJIFHGLK"
}


def best_third_rows(group_tables: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """Return the eight best third-placed teams using the available ranking fields."""

    candidates: list[dict[str, Any]] = []
    for group, table in group_tables.items():
        if len(table) < 3:
            continue
        row = dict(table[2])
        row["group"] = group
        candidates.append(row)

    return sorted(
        candidates,
        key=lambda row: (
            row.get("points", 0),
            row.get("goal_diff", 0),
            row.get("goals_for", 0),
            row["group"],
        ),
        reverse=True,
    )[:8]


def resolve_best_third_assignments(
    group_tables: dict[str, list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    """Map every official best-third slot to its FIFA Annexe C team."""

    selected = best_third_rows(group_tables)
    selected_by_group = {str(row["group"]): row for row in selected}
    key = "".join(sorted(selected_by_group))

    allocation = FIFA_2026_THIRD_PLACE_ALLOCATION.get(key)
    if allocation is None:
        raise ValueError(
            "No FIFA 2026 best-third allocation for group combination "
            f"{key!r}; expected eight distinct groups."
        )

    return {
        winner_group: selected_by_group[third_group]
        for winner_group, third_group in zip(THIRD_PLACE_COLUMNS, allocation)
    }


def build_round_of_32_pairings(
    group_tables: dict[str, list[dict[str, Any]]],
) -> list[tuple[str, int, str, str]]:
    """Build the 16 official Round-of-32 pairings in FIFA match-number order."""

    winners = {group: table[0]["team"] for group, table in group_tables.items() if table}
    runners_up = {
        group: table[1]["team"]
        for group, table in group_tables.items()
        if len(table) >= 2
    }
    third_assignments = resolve_best_third_assignments(group_tables)

    def third(group: str) -> str:
        return str(third_assignments[group]["team"])

    required_groups = set("ABCDEFGHIJKL")
    if set(winners) != required_groups or set(runners_up) != required_groups:
        raise ValueError("FIFA 2026 Round of 32 requires standings for groups A-L.")

    return [
        ("r32_73", 73, runners_up["A"], runners_up["B"]),
        ("r32_74", 74, winners["E"], third("E")),
        ("r32_75", 75, winners["F"], runners_up["C"]),
        ("r32_76", 76, winners["C"], runners_up["F"]),
        ("r32_77", 77, winners["I"], third("I")),
        ("r32_78", 78, runners_up["E"], runners_up["I"]),
        ("r32_79", 79, winners["A"], third("A")),
        ("r32_80", 80, winners["L"], third("L")),
        ("r32_81", 81, winners["D"], third("D")),
        ("r32_82", 82, winners["G"], third("G")),
        ("r32_83", 83, runners_up["K"], runners_up["L"]),
        ("r32_84", 84, winners["H"], runners_up["J"]),
        ("r32_85", 85, winners["B"], third("B")),
        ("r32_86", 86, winners["J"], runners_up["H"]),
        ("r32_87", 87, winners["K"], third("K")),
        ("r32_88", 88, runners_up["D"], runners_up["G"]),
    ]


OFFICIAL_NEXT_ROUND_SPECS: dict[str, list[tuple[str, int, str, str]]] = {
    "round_of_16": [
        ("r16_89", 89, "r32_74", "r32_77"),
        ("r16_90", 90, "r32_73", "r32_75"),
        ("r16_91", 91, "r32_76", "r32_78"),
        ("r16_92", 92, "r32_79", "r32_80"),
        ("r16_93", 93, "r32_83", "r32_84"),
        ("r16_94", 94, "r32_81", "r32_82"),
        ("r16_95", 95, "r32_86", "r32_88"),
        ("r16_96", 96, "r32_85", "r32_87"),
    ],
    "quarter_finals": [
        ("qf_97", 97, "r16_89", "r16_90"),
        ("qf_98", 98, "r16_93", "r16_94"),
        ("qf_99", 99, "r16_91", "r16_92"),
        ("qf_100", 100, "r16_95", "r16_96"),
    ],
    "semi_finals": [
        ("sf_101", 101, "qf_97", "qf_98"),
        ("sf_102", 102, "qf_99", "qf_100"),
    ],
}
